### ISSUE TITLE
Vite

### ISSUE THREAD

**Issue by lishaduck** [PSDTools/app#12]
[Vite](https://vitejs.dev/) is framework agnostic, and its only want is a single HTML file. Since Flutter makes SPAs, not MPAs, we can bundle it through Vite if we want. This is important if we want offline because we'll have to use vite-plugin-pwa until flutter/flutter#60069 is resolved.

**Comment by ParkerH27** [comment]
Thank you for adding the this is important part... usually I have no clue what your talking about and why it matters and that helps alot!

**Comment by lishaduck** [comment]
You're welcome!

**Comment by lishaduck** [comment]
Adding PWA support has gradually been accomplished within Flutter itself, so while it's not done, I feel it's safe to close this. We don't need an additional build step.
