### ISSUE TITLE
App routing issues

### ISSUE THREAD

**Issue by PetalCat** [PSDTools/app#160]
This's just an issue for an issue.
Honestly, Idk why this is/how this became broken.

**Comment by PetalCat** [comment]
My thought is that the issue is with the new wrapper cause it worked before we moved wrappers... Also @lishaduck idk if you have seen this issue

**Comment by PetalCat** [comment]
I got routing to route to GPA calculator by adding it to the auto tabs router routes. It still does the weird thing where you if you hit home it changes the address but still goes to the right place

**Comment by lishaduck** [comment]
I think #187 should fix this.

**Comment by lishaduck** [comment]
I forgot to close this w/ #187
