### ISSUE TITLE
Failing Test

### ISSUE THREAD

**Issue by lishaduck** [PSDTools/app#193]
### What happened?

Bootstrap test failed.

### Reproduction steps

n/a

### What should have happened?

Shouldn't fail.

### Date

Sep. 13th

### What device are you seeing the problem on?

Mac

### What platforms are you seeing the problem on? If on Web, also select browser.

MacOS

### Context

I've been trying to fix this, but I can't figure out the issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lishaduck** [comment]
How's this goin', @ParkerH27?

**Comment by PetalCat** [comment]
I'mma be real, confusingly

**Comment by lishaduck** [comment]
Yeah. That was my experience. Did you see the branch I pushed w/my try @ fixing it?

**Comment by lishaduck** [comment]
## Context:

#187 was fine until it was rebased atop https://github.com/PSDTools/app/commit/491b9b673f612550c583cd76230abf8f9127cca5, which looks to be a completely unrelated change.

<details><summary>Logs:</summary>

```console
'package:flutter_test/src/binding.dart': Failed assertion: line 1332 pos 12: 'inTest': is not true.
dart:core                                           _AssertionError._throwNew
package:flutter_test/src/binding.dart 1332:12       AutomatedTestWidgetsFlutterBinding.scheduleAttachRootWidget
package:flutter/src/widgets/binding.dart 1095:7     runApp
package:pirate_code/app/app.dart 79:5               App.bootstrap
===== asynchronous gap ===========================
dart:async                                          _CustomZone.registerBinaryCallback
test/app/app_test.dart 93:11                        main.<fn>.<fn>.<fn>
package:matcher                                     expectLater
package:flutter_test/src/widget_tester.dart 491:25  expectLater
test/app/app_test.dart 91:13                        main.<fn>.<fn>

This test failed after it had already completed.
Make sure to use a matching library which informs the test runner
of pending async work.
dart:core                                           _AssertionError._throwNew
package:flutter_test/src/binding.dart 1332:12       AutomatedTestWidgetsFlutterBinding.scheduleAttachRootWidget
package:flutter/src/widgets/binding.dart 1095:7     runApp
package:pirate_code/app/app.dart 79:5               App.bootstrap
===== asynchronous gap ===========================
dart:async                                          _CustomZone.registerBinaryCallback
test/app/app_test.dart 93:11                        main.<fn>.<fn>.<fn>
package:matcher                                     expectLater
package:flutter_test/src/widget_tester.dart 491:25  expectLater
test/app/app_test.dart 91:13                        main.<fn>.<fn>

00:29 +30 -2: Some tests failed.
Failing Tests:
 - test/app/app_test.dart 
        - [ERROR] Bootstrapping Tests! Test the boots...
        - [ERROR] Bootstrapping Tests! Test the boots...
```

</details>

Previous branch to fix test: [`fix-test`](https://github.com/PSDTools/app/tree/fix-test)

**Comment by lishaduck** [comment]
Hmmm. It seems to be pretty flaky, seeing as it failed on merge queues and succeeded on pushes. Let's wait and see.

**Comment by lishaduck** [comment]
Nope. It's flaky, but at least we know that.
It's consistently failing on my machine.

**Comment by lishaduck** [comment]
Reposting this to keep threads on topic:

> > > You wanna tackle this next after #193, @ParkerH27?
> > 
> > I guess so.... #193 is brain breaking
> 
> Yeah. Flaky tests are no fun. Did you look at 57339e90d313f7fb0ad77db5eb6451745276de19? I've found [invertase](https://invertase.io)'s [_Assertions In Dart And Flutter Tests: An (Now For Sure) Ultimate Cheat Sheet_](https://invertase.io/blog/assertions-in-dart-and-flutter-tests-now-for-sure-an-ultimate-cheat-sheet) to be quite useful. Also [_Flaky Tests: Getting Rid Of A Living Nightmare In Testing_](https://www.smashingmagazine.com/2021/04/flaky-tests-living-nightmare/) is a good article on why tests flake.
