### ISSUE TITLE
Use Sentry Tools

### ISSUE THREAD

**Issue by lishaduck** [PSDTools/app#34]
> Would using [Codecov](https://about.codecov.io/language/dart/) be more effective than our current testing setup?
> Also, while I'm thinking about Sentry, we should see if Pattonville has a preferred logging framework because while Sentry [supports](https://sentry.io/for/flutter/) Flutter, it doesn't let multiple users use it on the free plan.
>
> _Originally posted by @lishaduck in https://github.com/PSDTools/app/issues/28#issuecomment-1551972427_

Having thought about it, I think using a logging framework is a good idea, so we'll need to ask if the district has a Sentry plan. We could also set up Codecov.
Having looked into it, both Sentry and Codecov have a (free!) student plan through GitHub though, so maybe we wouldn't need to get seats on the district's plan. Which we both know they probably wouldn't let us do. 😁

**Comment by lishaduck** [comment]
Also, they have a [dedicated FastAPI integration](https://sentry.io/for/python/?platform=sentry.python.fastapi).

**Comment by ParkerH27** [comment]
I dont have a clue what any of this means

**Comment by lishaduck** [comment]
It'll let up monitor if there are crashes or memory leaks once we deploy, and we can `print` on deployed devices for debugging and still see it.

**Comment by lishaduck** [comment]
I think we're fine. We can re-visit this later if needed.
