### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by lishaduck** [PSDTools/app#44]
So...Netlify works for now, but when we start querying the Python server, we'll need something different.
Options:
- [webapp.io](https://webapp.io/) — I've used this tool before. I didn't like it, but it does what we need. It's a full-stack review environment and deployment service that uses a concurrent version of docker called [Firecracker](https://firecracker-microvm.github.io/), which is what powers [AWS Lambda](https://aws.amazon.com/lambda/).
- [Azure](https://azure.microsoft.com/en-us/products/functions/) — Comes with the student developer plan, but it's quite limited in both free and [out-of-the-box](https://azure.microsoft.com/en-us/products/app-service/static/). I don't want to, say, have to learn [Kubernetes](https://azure.microsoft.com/en-us/products/kubernetes-service/) just to do what I can do with the click of a button on Netlify. However, It has a tutorial on [serverless FastAPI functions](https://learn.microsoft.com/en-us/samples/azure-samples/fastapi-on-azure-functions/azure-functions-python-create-fastapi-app/) and a more advanced tutorial for [non-FastAPI serverless functions](https://learn.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-python?pivots=python-mode-decorators), so it might work. However, it comes with 1 million free requests a month,[^1] so maybe pricing ain't an issue.
- (GCP (Google Cloud Platform))[https://cloud.google.com/run/docs/quickstarts/build-and-deploy/deploy-python-service]
- local hosting (I (@PetalCat) have a machine for VMs and a network) I think this is a last-ditch option and can only be used for devin'.

[^1]: In case you were wondering, that's the same as AWS Lambda's free plan.

**Comment by PetalCat** [comment]
Already used a bunch of all of my free azure $100

**Comment by lishaduck** [comment]
Yeah. I, for one, just let my 300 expire. Silly me.

**Comment by lishaduck** [comment]
It was decided to use Azure.
