### ISSUE TITLE
Code Time

### ISSUE THREAD

**Issue by PetalCat** [PSDTools/app#47]
We need to track our total code time for the ELO to prove our work.

This looked like a good solution: [Code Time](https://marketplace.visualstudio.com/items?itemName=softwaredotcom.swdc-vscode#:~:text=Click%20Dashboard%20to%20open%20your,spent%20in%20your%20editor%20today.).

**Comment by lishaduck** [comment]
It's not still developed, and there seem to be a lot of bugs. They seem to have copied [Wakatime](https://wakatime.com/), so maybe we should use the original.

**Comment by lishaduck** [comment]
Looking more a Wakatime, it only gives the last two weeks on a dashboard, but we could still export the data as csv. More work, but less buggy, better support? I guess.

**Comment by lishaduck** [comment]
I've sent a Wakatime invite. Let's see if it works.
