### ISSUE TITLE
Crude App for Viewing Hardcoded Tokens

### ISSUE THREAD

**Issue by ParkerH27** [PSDTools/app#9]
For students.
```[tasklist]
### Tasks
- [x] Get a (fake) number on the screen
- [ ] https://github.com/PSDTools/app/pull/104
```

**Comment by ParkerH27** [comment]
Is this client side? Hard coded into the local app?

**Comment by lishaduck** [comment]
Yes.

**Comment by ParkerH27** [comment]
Got a little bored today while working on the crude app 👀
![coin](https://user-images.githubusercontent.com/91337218/233531757-ab1c5962-dfd3-4d5f-a7e7-ddfb3cbcf195.png)

**Comment by EthanA1** [comment]
I've got a couple of designs if anyone's interested.

**Comment by lishaduck** [comment]
Sure, @EthanA1. Send them my way! Also, @ParkerH27, remember to "commit early and often," so that it gets deployed.

**Comment by EthanA1** [comment]
Okay, I have a canva link, it seems easier that trying to send all the pictures at once.
https://www.canva.com/design/DAFgqBjyUGU/5cBdKEh0cF2Ge0WjlSHdcg/edit?utm_content=DAFgqBjyUGU&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by lishaduck** [comment]
Thanks! They look good!

**Comment by ParkerH27** [comment]
<img width="526" alt="Screen Shot 2023-04-21 at 12 20 55 PM" src="https://user-images.githubusercontent.com/91337218/233697354-9d7a1618-eed6-4d11-9bde-cacf52a1d78d.png">

**Comment by lishaduck** [comment]
Nice! On second thought, that's just a mock, right?

**Comment by ParkerH27** [comment]
I wish it wasnt

**Comment by lishaduck** [comment]
Ehhh. So fix it! 🤣

**Comment by lishaduck** [comment]
FastAPI be awesome!

**Comment by ParkerH27** [comment]
This might work for recreating the concept

https://youtu.be/UsFq21gYn5Q

**Comment by lishaduck** [comment]
So the function we need is `GridView.count()`

**Comment by PetalCat** [comment]
At the moment our wallet should literally just be a screen with a number on it..... Then we have to figure out my best friend.... Authentication

**Comment by PetalCat** [comment]
Then once authentication is figured out with the server and the client then we can build our blockchain

**Comment by lishaduck** [comment]
Naa, skip that. We
- learn Flutter,
- build a basic app with a number and a not completely awful UI, and get the UI to represent what we want,
- then build a basic auth-less server
- then remove the placeholders
- then read the [Bitcoin white paper](https://bitcoin.org/bitcoin.pdf)

At that point, we look at [FastAPI's Auth docs](https://fastapi.tiangolo.com/features/#security-and-authentication).
Seems simpler, and more TTD like.

**Comment by PetalCat** [comment]
I think my dad found a python library for blockchain I think it was called something like Open Blockchain so instead of reading the white paper and making one ourselves we could try and find a library to do it

**Comment by lishaduck** [comment]
Google doesn't show it, and I've already looked through PyPI:

Requoting the email for both transparency and ease of access.

> A quick search shows these: 
> 
> Blockchain:
> 
> - https://pypi.org/project/easy-blockchain/
> - https://pypi.org/project/blockchain-lab/
> - https://pypi.org/project/simple-blockchain/
> 
> Servers:
> 
> - https://pypi.org/project/fly-server/
> - https://pypi.org/project/quickhttp/ (not what you want, but looked interesting for me, so I wrote it down)
> - https://pypi.org/project/aiosftp/
> - https://pypi.org/project/proxy.py/
> - https://pypi.org/project/servepy/
> - Pulled these up earlier, but forgot to send them to you.

**Comment by PetalCat** [comment]
Okay not a library...

This is what he sent me:
http://docs.openchain.org/en/latest/general/overview.html

I don't know if it's exactly what we want to use but it at least has the concepts of a ledger outlined

**Comment by lishaduck** [comment]
Ahh. `.NET`-based server software. Still, might be useful.

**Comment by PetalCat** [comment]
You understand the idea of the blockchain though.... Decentralized data storage and verification

**Comment by lishaduck** [comment]
> You understand the idea of the blockchain though?.... Decentralized data storage and verification

A ledger is a form of decentralized data storage and verification via immutable records in the form of a linked list that uses hashes on blocks to identify the parent block, and which is only appended to, with existing content never being modified.

**Comment by PetalCat** [comment]
Point made.

**Comment by PetalCat** [comment]
Moar Blockchains

https://appwrite.io/cloud?keyword=&utm_term=&utm_campaign=HD-Appwrite-PMax-NA-Prospecting&utm_source=google&utm_medium=cpc&hsa_acc=8189217294&hsa_cam=17430228429&hsa_grp=&hsa_ad=&hsa_src=&hsa_tgt=&hsa_kw=&hsa_mt=&hsa_net=adwords&hsa_ver=3&gad=1&gclid=Cj0KCQjwi46iBhDyARIsAE3nVrawiHJ50i7PmwSzBye9zwNhPEml7axiPIcRoY6UVuc9hKb4YhlQpd8aAqz9EALw_wcB


https://www.analyticsinsight.net/top-10-open-source-blockchain-platforms-to-explore-in-2022/

**Comment by lishaduck** [comment]
Fluttery things don't appear to support Python.
More blockchains have a disclaimer saying it's all paid sponsorships. And none of them have a Python API.

**Comment by lishaduck** [comment]
I'm going to go through the tutorial. Do you have anything unsaved, or that you don't want to be overwritten?

**Comment by PetalCat** [comment]
Not that I know of!

**Comment by lishaduck** [comment]
> Not that I know of!

OK! I'll just delete everything then.

**Comment by lishaduck** [comment]
Routing is infuriating. I can't get it to mutate the state right to change the page and the URL.

**Comment by lishaduck** [comment]
nvm,[^1] figured it out

[^1]: in case you were wondering, that wasn't an ad for nodejs

**Comment by lishaduck** [comment]
Got tired of using `go_router`, trying [`auto_route`](https://pub.dev/packages/auto_route).

**Comment by lishaduck** [comment]
_**Note:** #23 is currently tracking our status for fixing the runtime errors._

**Comment by PetalCat** [comment]
![Screenshot_20230518_165355_Chrome.jpg](https://github.com/PSDTools/app/assets/58083460/4c16fb33-c6a7-457a-acbf-090b2313dfef)

**Comment by lishaduck** [comment]
Sure is better than it used to be! Not super good, but not completely awful.

**Comment by lishaduck** [comment]
Wait. Where was the favorites page?

**Comment by PetalCat** [comment]
It's there... It is just white on white.... If you soom I. You can see it

**Comment by lishaduck** [comment]
Ahh. That'll need to get fixed. Are you patching it, or will I need to make a hotfix commit?

**Comment by PetalCat** [comment]
I probably won't touch git until tomorrow... Then if it still isn't done... I'll go in and try to fix it

**Comment by lishaduck** [comment]
Ok. I'm not messing with it anymore myself, so that seems reasonable. Signing off!
Oh, but before I leave-leave, have you seen #33 and #34?

**Comment by PetalCat** [comment]
Just looked at them I'll look at them again tomorrow... I need my brain to be working before I think about that

**Comment by lishaduck** [comment]
Can you check #32 and see if it's resolved?

**Comment by ParkerH27** [comment]
<img width="1680" alt="Screen Shot 2023-05-23 at 4 17 21 PM" src="https://github.com/PSDTools/app/assets/91337218/82b93970-d654-4fab-999c-5ee809d6b39d">
👀

**Comment by lishaduck** [comment]
Wow!

**Comment by PetalCat** [comment]
Now I gotta to build it for real

**Comment by ParkerH27** [comment]
Figma is an addiction
<img width="1680" alt="Screen Shot 2023-05-23 at 7 29 37 PM" src="https://github.com/PSDTools/app/assets/91337218/a7153b66-5321-45ba-9b72-6e776a972563">

**Comment by lishaduck** [comment]
Now, if only we were sixteen and this was for a paid college course: [Sketch](https://www.sketch.com/).
